/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ot.micropay.order.model;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class OrderStatus extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7926440192309515461L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"OrderStatus\",\"namespace\":\"com.ot.micropay.order.model\",\"fields\":[{\"name\":\"OrderId\",\"type\":\"string\"},{\"name\":\"customerId\",\"type\":\"string\"},{\"name\":\"status\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<OrderStatus> ENCODER =
      new BinaryMessageEncoder<OrderStatus>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<OrderStatus> DECODER =
      new BinaryMessageDecoder<OrderStatus>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<OrderStatus> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<OrderStatus> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<OrderStatus>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this OrderStatus to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a OrderStatus from a ByteBuffer. */
  public static OrderStatus fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence OrderId;
  @Deprecated public java.lang.CharSequence customerId;
  @Deprecated public java.lang.CharSequence status;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public OrderStatus() {}

  /**
   * All-args constructor.
   * @param OrderId The new value for OrderId
   * @param customerId The new value for customerId
   * @param status The new value for status
   */
  public OrderStatus(java.lang.CharSequence OrderId, java.lang.CharSequence customerId, java.lang.CharSequence status) {
    this.OrderId = OrderId;
    this.customerId = customerId;
    this.status = status;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return OrderId;
    case 1: return customerId;
    case 2: return status;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: OrderId = (java.lang.CharSequence)value$; break;
    case 1: customerId = (java.lang.CharSequence)value$; break;
    case 2: status = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'OrderId' field.
   * @return The value of the 'OrderId' field.
   */
  public java.lang.CharSequence getOrderId() {
    return OrderId;
  }

  /**
   * Sets the value of the 'OrderId' field.
   * @param value the value to set.
   */
  public void setOrderId(java.lang.CharSequence value) {
    this.OrderId = value;
  }

  /**
   * Gets the value of the 'customerId' field.
   * @return The value of the 'customerId' field.
   */
  public java.lang.CharSequence getCustomerId() {
    return customerId;
  }

  /**
   * Sets the value of the 'customerId' field.
   * @param value the value to set.
   */
  public void setCustomerId(java.lang.CharSequence value) {
    this.customerId = value;
  }

  /**
   * Gets the value of the 'status' field.
   * @return The value of the 'status' field.
   */
  public java.lang.CharSequence getStatus() {
    return status;
  }

  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(java.lang.CharSequence value) {
    this.status = value;
  }

  /**
   * Creates a new OrderStatus RecordBuilder.
   * @return A new OrderStatus RecordBuilder
   */
  public static com.ot.micropay.order.model.OrderStatus.Builder newBuilder() {
    return new com.ot.micropay.order.model.OrderStatus.Builder();
  }

  /**
   * Creates a new OrderStatus RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new OrderStatus RecordBuilder
   */
  public static com.ot.micropay.order.model.OrderStatus.Builder newBuilder(com.ot.micropay.order.model.OrderStatus.Builder other) {
    return new com.ot.micropay.order.model.OrderStatus.Builder(other);
  }

  /**
   * Creates a new OrderStatus RecordBuilder by copying an existing OrderStatus instance.
   * @param other The existing instance to copy.
   * @return A new OrderStatus RecordBuilder
   */
  public static com.ot.micropay.order.model.OrderStatus.Builder newBuilder(com.ot.micropay.order.model.OrderStatus other) {
    return new com.ot.micropay.order.model.OrderStatus.Builder(other);
  }

  /**
   * RecordBuilder for OrderStatus instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<OrderStatus>
    implements org.apache.avro.data.RecordBuilder<OrderStatus> {

    private java.lang.CharSequence OrderId;
    private java.lang.CharSequence customerId;
    private java.lang.CharSequence status;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.ot.micropay.order.model.OrderStatus.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.OrderId)) {
        this.OrderId = data().deepCopy(fields()[0].schema(), other.OrderId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.customerId)) {
        this.customerId = data().deepCopy(fields()[1].schema(), other.customerId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.status)) {
        this.status = data().deepCopy(fields()[2].schema(), other.status);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing OrderStatus instance
     * @param other The existing instance to copy.
     */
    private Builder(com.ot.micropay.order.model.OrderStatus other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.OrderId)) {
        this.OrderId = data().deepCopy(fields()[0].schema(), other.OrderId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.customerId)) {
        this.customerId = data().deepCopy(fields()[1].schema(), other.customerId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.status)) {
        this.status = data().deepCopy(fields()[2].schema(), other.status);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'OrderId' field.
      * @return The value.
      */
    public java.lang.CharSequence getOrderId() {
      return OrderId;
    }

    /**
      * Sets the value of the 'OrderId' field.
      * @param value The value of 'OrderId'.
      * @return This builder.
      */
    public com.ot.micropay.order.model.OrderStatus.Builder setOrderId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.OrderId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'OrderId' field has been set.
      * @return True if the 'OrderId' field has been set, false otherwise.
      */
    public boolean hasOrderId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'OrderId' field.
      * @return This builder.
      */
    public com.ot.micropay.order.model.OrderStatus.Builder clearOrderId() {
      OrderId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'customerId' field.
      * @return The value.
      */
    public java.lang.CharSequence getCustomerId() {
      return customerId;
    }

    /**
      * Sets the value of the 'customerId' field.
      * @param value The value of 'customerId'.
      * @return This builder.
      */
    public com.ot.micropay.order.model.OrderStatus.Builder setCustomerId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.customerId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'customerId' field has been set.
      * @return True if the 'customerId' field has been set, false otherwise.
      */
    public boolean hasCustomerId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'customerId' field.
      * @return This builder.
      */
    public com.ot.micropay.order.model.OrderStatus.Builder clearCustomerId() {
      customerId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'status' field.
      * @return The value.
      */
    public java.lang.CharSequence getStatus() {
      return status;
    }

    /**
      * Sets the value of the 'status' field.
      * @param value The value of 'status'.
      * @return This builder.
      */
    public com.ot.micropay.order.model.OrderStatus.Builder setStatus(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.status = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'status' field has been set.
      * @return True if the 'status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'status' field.
      * @return This builder.
      */
    public com.ot.micropay.order.model.OrderStatus.Builder clearStatus() {
      status = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public OrderStatus build() {
      try {
        OrderStatus record = new OrderStatus();
        record.OrderId = fieldSetFlags()[0] ? this.OrderId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.customerId = fieldSetFlags()[1] ? this.customerId : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.status = fieldSetFlags()[2] ? this.status : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<OrderStatus>
    WRITER$ = (org.apache.avro.io.DatumWriter<OrderStatus>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<OrderStatus>
    READER$ = (org.apache.avro.io.DatumReader<OrderStatus>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
