server.port: 9083

management.server.port: 9084

spring.data.rest.basePath: /api
spring.data.cassandra.keyspace-name: subbu
spring:
    kafka:
      consumer:
       topics: users
       bootstrap-servers: localhost:9092
       group-id: group-id
       key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
       alue-deserializer: org.apache.kafka.common.serialization.StringDeserializer
---
spring:
  data:
    cassandra:
      port: 9042
      contact-points: 10.194.39.37
      schema-action: create-if-not-exists
      local-datacenter: datacenter1
---
spring.profiles: kubernetes

springfox:
  documentation:
    auto-startup: false
management.endpoint.restart.enabled: true


     
